// app/layout.js
import Navbar from "@/components/Navbar";
import "./globals.css";
// import 'bootstrap/dist/css/bootstrap.min.css';
import FooterComponent from "@/components/Footer";
import { CurrencyProvider } from "@/app/context/CurrencyContext";
import { ThemeProvider } from '../context/ThemeContext';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#FAFBFFCC] ">
        <ThemeProvider>
          <CurrencyProvider>
            <Navbar />
            <main className="pt-[56px] mx-auto">
              {children}
              <FooterComponent />
            </main>
          </CurrencyProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
